// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoKjwl7ZZuCDDK9N2qyQaSPRaQ3dY9SEU',
    appId: '1:1081921816948:web:5771fa4a6dd7f059834421',
    messagingSenderId: '1081921816948',
    projectId: 'proyectov2-d9bc1',
    authDomain: 'proyectov2-d9bc1.firebaseapp.com',
    storageBucket: 'proyectov2-d9bc1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQfYxbAlpdB1Z0ilZgIlsZsWypIa30UQA',
    appId: '1:1081921816948:android:34989731fb897415834421',
    messagingSenderId: '1081921816948',
    projectId: 'proyectov2-d9bc1',
    storageBucket: 'proyectov2-d9bc1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtkC_F2NjBv9aEyz4EnY149hn7WCATITA',
    appId: '1:1081921816948:ios:2ed84ba993dd43cc834421',
    messagingSenderId: '1081921816948',
    projectId: 'proyectov2-d9bc1',
    storageBucket: 'proyectov2-d9bc1.appspot.com',
    iosBundleId: 'com.example.proyectoV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtkC_F2NjBv9aEyz4EnY149hn7WCATITA',
    appId: '1:1081921816948:ios:bdd67fcaae69a733834421',
    messagingSenderId: '1081921816948',
    projectId: 'proyectov2-d9bc1',
    storageBucket: 'proyectov2-d9bc1.appspot.com',
    iosBundleId: 'com.example.proyectoV2.RunnerTests',
  );
}
